### ISSUE TITLE
Decorations are not applied to the capture groups

### ISSUE THREAD

**Issue by JavaSpyder** [MickaelBlet/highlight-regex#1]
## Issue
When attempting to select capture groups for decoration, the decoration is not applied to the correct characters.

### Configuration
```
"highlight.regex.regexes": [
    {
      "languageIds": [
        "plaintext"
      ],
      "regexes": [
        {
          "regex": "match (ME) and (ME)",
          "decorations": [
            {
              "index": 1,
              "fontStyle": "italic",
            },
            {
              "index": 2,
              "fontWeight": "bold",
            }
          ]
        },
        {
          "regex": "and (THIS TOO)",
          "decorations": [
            {
              "index": 1,
              "fontWeight": "bold",
            },
          ]
        }
      ]
    },
  ],
```

### Original File (test.txt)
`match ME and ME and THIS TOO`

### Expected result
`match _ME_ and **ME** and **THIS TOO**`

### Actual result
`_ma_**tc**h ME and ME **and THIS** TOO`

### My Visual Studio Code Info
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Extensions: Tested in a profile with only Highlight - Regex installed.

**Comment by MickaelBlet** [comment]
You can add groups
```
"highlight.regex.regexes": [
    {
      "languageIds": [
        "plaintext"
      ],
      "regexes": [
        {
          "regex": "(match )(ME)( and )(ME)",
          "decorations": [
            {
              "index": 2,
              "fontStyle": "italic",
            },
            {
              "index": 4,
              "fontWeight": "bold",
            }
          ]
        },
        {
          "regex": "(and )(THIS TOO)",
          "decorations": [
            {
              "index": 2,
              "fontWeight": "bold",
            },
          ]
        }
      ]
    },
  ],
```

I will try to do this automatically.

**Comment by MickaelBlet** [comment]
The commit 3eb87dfff278b19efda4b06c17a366cb9355e663 solved the issue.
