### ISSUE TITLE
Invalid regular expression in latest version of vscode

### ISSUE THREAD

**Issue by ctf0** [MickaelBlet/highlight-regex#2]
```
SyntaxError: Invalid regular expression: /(((?<=((?: +)?)(`{3}\w+\s)))((?:.|\s)*)(?)((?=(\s)((?: +)?)(`{3}))))/g: Invalid group
```

```
Version: 1.82.0-insider
Commit: 501baeb5e07b5a404f862d922bacb93771d91331
Date: 2023-08-18T05:34:41.801Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 21.6.0
```

**Comment by MickaelBlet** [comment]
Can you give me your original regex string please?

I don't understand why adding automatic group added '(?)'.

**Comment by ctf0** [comment]
> Can you give me your original regex string please?

this is the regex causing the issue ```((?<=( +)?`{3}\\w+\\s)(.|\\s)*?(?=\\s( +)?`{3}))``` for some reason its giving the error

https://regex101.com/r/SnLLlF/1

**Comment by MickaelBlet** [comment]
You can fix it with this regex ```((?<=( +)?`{3}\\w+\\s)(.|\\s)*(?=\\s( +)?`{3}))```.
But I will correct that soon.

**Comment by ctf0** [comment]
sure np, thanks for ur help & support ❤️

**Comment by MickaelBlet** [comment]
The commit 4b10ded933e3369f69ca90d10cc7b4f2518af016 solved the issue.
