### ISSUE TITLE
Make it remeber previous tabs

### ISSUE THREAD

**Issue by abdullah1116** [MickaelBlet/highlight-regex#4]
hi, i'm using your excellent extension and would like to request a new feature. Currently, when switching between files, the extension reprocesses them, which can be time-consuming.

To enhance the user experience, could you implement a feature that remembers the highlights of files until they are closed? This would significantly reduce the time required for file switching and improve overall performance.

**Comment by MickaelBlet** [comment]
The commit https://github.com/MickaelBlet/highlight-regex/commit/df9059a4a5863b68c8e1d5de246ccce787ca3f10  solved the issue.
